### ISSUE TITLE
Countly is not accessible

### ISSUE THREAD

**Issue by GaneshShetty951** [Countly/countly-sample-ios#13]
I have installed Countly through pods when i enabled Notification from Countly Documentation, CountlyNSE folder created and inside **NotificationService.swift** file created i edited that file as mentioned in Countly documentaion but that giving error _No Such Module 'Countly'_ .

`import UserNotifications
    //import Countly

    class NotificationService: UNNotificationServiceExtension {
    var contentHandler: ((UNNotificationContent) -> Void)?
    var bestAttemptContent: UNMutableNotificationContent?

    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.contentHandler = contentHandler
        bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)
        
        //delete existing template code, and add this line
       //CountlyNotificationService.didReceive(request, withContentHandler: contentHandler);
    }

    override func serviceExtensionTimeWillExpire() {
        // Called just before the extension will be terminated by the system.
        // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
        if let contentHandler = contentHandler, let bestAttemptContent =  bestAttemptContent {
            contentHandler(bestAttemptContent)
        }
    }
}`

**Comment by erkanyildiz** [comment]
This is a known CocoaPods issue where you add a subspec for an extension target on a Swift project. https://github.com/CocoaPods/CocoaPods/issues/7733

<img width="586" alt="cocoapodstable" src="https://user-images.githubusercontent.com/1222652/43363101-bea4b1ea-9337-11e8-961d-27fed26c8245.png">

Please disable CocoaPods for Notification Service Extension target (CountlyNSE), and integrate `CountlyNotificationService` files manually:

1) Please delete these:

```
target 'CountlyNSE' do
...
end
```
from your `Podfile`, and keep only your main app target.


2) after you use `pod install` command, manually add `CountlyNotificationService.h` and `CountlyNotificationService.m` files to your Notification Service Extension target (`CountlyNSE`) from `Pods` directory.


3) Create a Swift Bridging Header file for your extension target.
File name should be `CountlyNSE-Bridging-Header.h` automatically.
And you should import `CountlyNotificationService.h` in it.

```
#import "CountlyNotificationService.h"
```

4) Under your extension target's `Build Settings` > `Objective-C Bridging Header` section, specify bridging header file's path.

e.g. `CountlyNSE/CountlyNSE-Bridging-Header.h`

5) Now you can call `CountlyNotificationService.didReceive(request, withContentHandler: contentHandler)` method in your `NotificationService.swift` file.
